LObject * l_quote(LObject * a1);
LObject * l_eval(LObject * a1);
LObject * l_lambda(LList  * a1, LList * a2);
LObject * l_let(LList * a1);
LObject * l_defun(char * a1, LList  * a2, LList * a3);
LObject * l_setq(LObject * a1, LObject * a2);
void l_while(LObject * a1, LObject * a2);
LObject * l_if(LObject * a1, LObject * a2, LObject * a3);
int l_not(LObject * a1);
LObject * l_or(LObject * a1, LObject * a2);
LObject * l_and(LObject * a1, LObject * a2);
LObject * l_greater(LObject * a1, LObject * a2);
int l_less(LObject * a1, LObject * a2);
int l_equal(LObject * a1, LObject * a2);
LObject * l_add(LObject * a1, LObject * a2);
LObject * l_substract(LObject * a1, LObject * a2);
LObject * l_multiply(LObject * a1, LObject * a2);
LObject * l_divide(LObject * a1, LObject * a2);
LObject * l_remainder(LObject * a1, LObject * a2);
LObject * l_truncate(LObject * a1);
int l_sgi();
int l_NeXT();
LObject * l_progn(LList * a1);
LObject * l_EvalLambda(LObject * a1, LList * a2);
LObject * l_EvalDefun(LList * a1);
LObject * l_car(LList  * a1);
LObject * l_cdr(LList  * a1);
LObject * l_cons(LObject * a1, LList  * a2);
void l_interest(LList  * a1);
void l_uninterest(LList  * a1);
void l_time_interests(float a1, char * a2, char * a3, char * a4);
void l_regtable();
void l_help(char * a1);
void l_morehelp(char * a1);
